# Generated by Django 4.2.2 on 2023-07-15 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_clientprofile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientprofile',
            name='city',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='post_code',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
