# Generated by Django 4.2.2 on 2023-07-01 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productbrand',
            name='image',
        ),
    ]
