# Generated by Django 4.2.2 on 2023-07-11 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='category'),
        ),
        migrations.AddField(
            model_name='productbrand',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='brand'),
        ),
    ]
