# Generated by Django 4.2.2 on 2023-07-11 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_category_image_productbrand_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='status',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='productbrand',
            name='status',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
